### ISSUE TITLE
Add wiki page about what do we do different than similar libraries

### ISSUE THREAD

**Issue by peterfication** [store2be/redux-belt#25]
https://github.com/pauldijou/redux-act
https://github.com/skellock/reduxsauce
https://github.com/modernserf/redux-action-schema
https://github.com/Bloomca/redux-tiles

**Comment by brainlessdeveloper** [comment]
Good idea, I would wait a bit until we have a more stable API though, what do you think?

**Comment by peterfication** [comment]
Yop just wanted to have an Issue to collect stuff. And we can already start it for some to also think about are we really different or do we want to adapt some ideas or change the description of the library to distinct it from the others.

One thing for example: We have a very minimal abstraction compared to [redux-tiles](https://github.com/Bloomca/redux-tiles) which has it's own DSL for creating reducers and so on.

**Comment by tomhoule** [comment]
https://github.com/store2be/redux-belt/wiki/Comparison-to-similar-projects
